// Code generated by thriftgo (0.4.5). DO NOT EDIT.

package order

import (
	"context"
	"fmt"
)

type Order struct {
	OrderId     string `thrift:"order_id,1" frugal:"1,default,string" json:"order_id"`
	UserId      string `thrift:"user_id,2" frugal:"2,default,string" json:"user_id"`
	AmountCents int64  `thrift:"amount_cents,3" frugal:"3,default,i64" json:"amount_cents"`
	Status      string `thrift:"status,4" frugal:"4,default,string" json:"status"`
	CreatedAt   string `thrift:"created_at,5" frugal:"5,default,string" json:"created_at"`
}

func NewOrder() *Order {
	return &Order{}
}

func (p *Order) InitDefault() {
}

func (p *Order) GetOrderId() (v string) {
	return p.OrderId
}

func (p *Order) GetUserId() (v string) {
	return p.UserId
}

func (p *Order) GetAmountCents() (v int64) {
	return p.AmountCents
}

func (p *Order) GetStatus() (v string) {
	return p.Status
}

func (p *Order) GetCreatedAt() (v string) {
	return p.CreatedAt
}
func (p *Order) SetOrderId(val string) {
	p.OrderId = val
}
func (p *Order) SetUserId(val string) {
	p.UserId = val
}
func (p *Order) SetAmountCents(val int64) {
	p.AmountCents = val
}
func (p *Order) SetStatus(val string) {
	p.Status = val
}
func (p *Order) SetCreatedAt(val string) {
	p.CreatedAt = val
}

func (p *Order) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("Order(%+v)", *p)
}

var fieldIDToName_Order = map[int16]string{
	1: "order_id",
	2: "user_id",
	3: "amount_cents",
	4: "status",
	5: "created_at",
}

type CreateOrderRequest struct {
	UserId         string `thrift:"user_id,1,required" frugal:"1,required,string" json:"user_id"`
	AmountCents    int64  `thrift:"amount_cents,2,required" frugal:"2,required,i64" json:"amount_cents"`
	IdempotencyKey string `thrift:"idempotency_key,3,required" frugal:"3,required,string" json:"idempotency_key"`
}

func NewCreateOrderRequest() *CreateOrderRequest {
	return &CreateOrderRequest{}
}

func (p *CreateOrderRequest) InitDefault() {
}

func (p *CreateOrderRequest) GetUserId() (v string) {
	return p.UserId
}

func (p *CreateOrderRequest) GetAmountCents() (v int64) {
	return p.AmountCents
}

func (p *CreateOrderRequest) GetIdempotencyKey() (v string) {
	return p.IdempotencyKey
}
func (p *CreateOrderRequest) SetUserId(val string) {
	p.UserId = val
}
func (p *CreateOrderRequest) SetAmountCents(val int64) {
	p.AmountCents = val
}
func (p *CreateOrderRequest) SetIdempotencyKey(val string) {
	p.IdempotencyKey = val
}

func (p *CreateOrderRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CreateOrderRequest(%+v)", *p)
}

var fieldIDToName_CreateOrderRequest = map[int16]string{
	1: "user_id",
	2: "amount_cents",
	3: "idempotency_key",
}

type CreateOrderResponse struct {
	Order    *Order `thrift:"order,1" frugal:"1,default,Order" json:"order"`
	Replayed bool   `thrift:"replayed,2" frugal:"2,default,bool" json:"replayed"`
}

func NewCreateOrderResponse() *CreateOrderResponse {
	return &CreateOrderResponse{}
}

func (p *CreateOrderResponse) InitDefault() {
}

var CreateOrderResponse_Order_DEFAULT *Order

func (p *CreateOrderResponse) GetOrder() (v *Order) {
	if !p.IsSetOrder() {
		return CreateOrderResponse_Order_DEFAULT
	}
	return p.Order
}

func (p *CreateOrderResponse) GetReplayed() (v bool) {
	return p.Replayed
}
func (p *CreateOrderResponse) SetOrder(val *Order) {
	p.Order = val
}
func (p *CreateOrderResponse) SetReplayed(val bool) {
	p.Replayed = val
}

func (p *CreateOrderResponse) IsSetOrder() bool {
	return p.Order != nil
}

func (p *CreateOrderResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CreateOrderResponse(%+v)", *p)
}

var fieldIDToName_CreateOrderResponse = map[int16]string{
	1: "order",
	2: "replayed",
}

type GetOrderRequest struct {
	OrderId string `thrift:"order_id,1,required" frugal:"1,required,string" json:"order_id"`
}

func NewGetOrderRequest() *GetOrderRequest {
	return &GetOrderRequest{}
}

func (p *GetOrderRequest) InitDefault() {
}

func (p *GetOrderRequest) GetOrderId() (v string) {
	return p.OrderId
}
func (p *GetOrderRequest) SetOrderId(val string) {
	p.OrderId = val
}

func (p *GetOrderRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetOrderRequest(%+v)", *p)
}

var fieldIDToName_GetOrderRequest = map[int16]string{
	1: "order_id",
}

type GetOrderResponse struct {
	Order *Order `thrift:"order,1" frugal:"1,default,Order" json:"order"`
}

func NewGetOrderResponse() *GetOrderResponse {
	return &GetOrderResponse{}
}

func (p *GetOrderResponse) InitDefault() {
}

var GetOrderResponse_Order_DEFAULT *Order

func (p *GetOrderResponse) GetOrder() (v *Order) {
	if !p.IsSetOrder() {
		return GetOrderResponse_Order_DEFAULT
	}
	return p.Order
}
func (p *GetOrderResponse) SetOrder(val *Order) {
	p.Order = val
}

func (p *GetOrderResponse) IsSetOrder() bool {
	return p.Order != nil
}

func (p *GetOrderResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetOrderResponse(%+v)", *p)
}

var fieldIDToName_GetOrderResponse = map[int16]string{
	1: "order",
}

type UpdateStatusRequest struct {
	OrderId string `thrift:"order_id,1,required" frugal:"1,required,string" json:"order_id"`
	Status  string `thrift:"status,2,required" frugal:"2,required,string" json:"status"`
}

func NewUpdateStatusRequest() *UpdateStatusRequest {
	return &UpdateStatusRequest{}
}

func (p *UpdateStatusRequest) InitDefault() {
}

func (p *UpdateStatusRequest) GetOrderId() (v string) {
	return p.OrderId
}

func (p *UpdateStatusRequest) GetStatus() (v string) {
	return p.Status
}
func (p *UpdateStatusRequest) SetOrderId(val string) {
	p.OrderId = val
}
func (p *UpdateStatusRequest) SetStatus(val string) {
	p.Status = val
}

func (p *UpdateStatusRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UpdateStatusRequest(%+v)", *p)
}

var fieldIDToName_UpdateStatusRequest = map[int16]string{
	1: "order_id",
	2: "status",
}

type UpdateStatusResponse struct {
	Order *Order `thrift:"order,1" frugal:"1,default,Order" json:"order"`
}

func NewUpdateStatusResponse() *UpdateStatusResponse {
	return &UpdateStatusResponse{}
}

func (p *UpdateStatusResponse) InitDefault() {
}

var UpdateStatusResponse_Order_DEFAULT *Order

func (p *UpdateStatusResponse) GetOrder() (v *Order) {
	if !p.IsSetOrder() {
		return UpdateStatusResponse_Order_DEFAULT
	}
	return p.Order
}
func (p *UpdateStatusResponse) SetOrder(val *Order) {
	p.Order = val
}

func (p *UpdateStatusResponse) IsSetOrder() bool {
	return p.Order != nil
}

func (p *UpdateStatusResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UpdateStatusResponse(%+v)", *p)
}

var fieldIDToName_UpdateStatusResponse = map[int16]string{
	1: "order",
}

type OrderError struct {
	Code    int32  `thrift:"code,1" frugal:"1,default,i32" json:"code"`
	Message string `thrift:"message,2" frugal:"2,default,string" json:"message"`
}

func NewOrderError() *OrderError {
	return &OrderError{}
}

func (p *OrderError) InitDefault() {
}

func (p *OrderError) GetCode() (v int32) {
	return p.Code
}

func (p *OrderError) GetMessage() (v string) {
	return p.Message
}
func (p *OrderError) SetCode(val int32) {
	p.Code = val
}
func (p *OrderError) SetMessage(val string) {
	p.Message = val
}

func (p *OrderError) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("OrderError(%+v)", *p)
}
func (p *OrderError) Error() string {
	return p.String()
}

var fieldIDToName_OrderError = map[int16]string{
	1: "code",
	2: "message",
}

type OrderService interface {
	CreateOrder(ctx context.Context, req *CreateOrderRequest) (r *CreateOrderResponse, err error)

	GetOrder(ctx context.Context, req *GetOrderRequest) (r *GetOrderResponse, err error)

	UpdateStatus(ctx context.Context, req *UpdateStatusRequest) (r *UpdateStatusResponse, err error)
}

type OrderServiceCreateOrderArgs struct {
	Req *CreateOrderRequest `thrift:"req,1" frugal:"1,default,CreateOrderRequest" json:"req"`
}

func NewOrderServiceCreateOrderArgs() *OrderServiceCreateOrderArgs {
	return &OrderServiceCreateOrderArgs{}
}

func (p *OrderServiceCreateOrderArgs) InitDefault() {
}

var OrderServiceCreateOrderArgs_Req_DEFAULT *CreateOrderRequest

func (p *OrderServiceCreateOrderArgs) GetReq() (v *CreateOrderRequest) {
	if !p.IsSetReq() {
		return OrderServiceCreateOrderArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *OrderServiceCreateOrderArgs) SetReq(val *CreateOrderRequest) {
	p.Req = val
}

func (p *OrderServiceCreateOrderArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *OrderServiceCreateOrderArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("OrderServiceCreateOrderArgs(%+v)", *p)
}

var fieldIDToName_OrderServiceCreateOrderArgs = map[int16]string{
	1: "req",
}

type OrderServiceCreateOrderResult struct {
	Success *CreateOrderResponse `thrift:"success,0,optional" frugal:"0,optional,CreateOrderResponse" json:"success,omitempty"`
	Err     *OrderError          `thrift:"err,1,optional" frugal:"1,optional,OrderError" json:"err,omitempty"`
}

func NewOrderServiceCreateOrderResult() *OrderServiceCreateOrderResult {
	return &OrderServiceCreateOrderResult{}
}

func (p *OrderServiceCreateOrderResult) InitDefault() {
}

var OrderServiceCreateOrderResult_Success_DEFAULT *CreateOrderResponse

func (p *OrderServiceCreateOrderResult) GetSuccess() (v *CreateOrderResponse) {
	if !p.IsSetSuccess() {
		return OrderServiceCreateOrderResult_Success_DEFAULT
	}
	return p.Success
}

var OrderServiceCreateOrderResult_Err_DEFAULT *OrderError

func (p *OrderServiceCreateOrderResult) GetErr() (v *OrderError) {
	if !p.IsSetErr() {
		return OrderServiceCreateOrderResult_Err_DEFAULT
	}
	return p.Err
}
func (p *OrderServiceCreateOrderResult) SetSuccess(x interface{}) {
	p.Success = x.(*CreateOrderResponse)
}
func (p *OrderServiceCreateOrderResult) SetErr(val *OrderError) {
	p.Err = val
}

func (p *OrderServiceCreateOrderResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *OrderServiceCreateOrderResult) IsSetErr() bool {
	return p.Err != nil
}

func (p *OrderServiceCreateOrderResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("OrderServiceCreateOrderResult(%+v)", *p)
}

var fieldIDToName_OrderServiceCreateOrderResult = map[int16]string{
	0: "success",
	1: "err",
}

type OrderServiceGetOrderArgs struct {
	Req *GetOrderRequest `thrift:"req,1" frugal:"1,default,GetOrderRequest" json:"req"`
}

func NewOrderServiceGetOrderArgs() *OrderServiceGetOrderArgs {
	return &OrderServiceGetOrderArgs{}
}

func (p *OrderServiceGetOrderArgs) InitDefault() {
}

var OrderServiceGetOrderArgs_Req_DEFAULT *GetOrderRequest

func (p *OrderServiceGetOrderArgs) GetReq() (v *GetOrderRequest) {
	if !p.IsSetReq() {
		return OrderServiceGetOrderArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *OrderServiceGetOrderArgs) SetReq(val *GetOrderRequest) {
	p.Req = val
}

func (p *OrderServiceGetOrderArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *OrderServiceGetOrderArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("OrderServiceGetOrderArgs(%+v)", *p)
}

var fieldIDToName_OrderServiceGetOrderArgs = map[int16]string{
	1: "req",
}

type OrderServiceGetOrderResult struct {
	Success *GetOrderResponse `thrift:"success,0,optional" frugal:"0,optional,GetOrderResponse" json:"success,omitempty"`
	Err     *OrderError       `thrift:"err,1,optional" frugal:"1,optional,OrderError" json:"err,omitempty"`
}

func NewOrderServiceGetOrderResult() *OrderServiceGetOrderResult {
	return &OrderServiceGetOrderResult{}
}

func (p *OrderServiceGetOrderResult) InitDefault() {
}

var OrderServiceGetOrderResult_Success_DEFAULT *GetOrderResponse

func (p *OrderServiceGetOrderResult) GetSuccess() (v *GetOrderResponse) {
	if !p.IsSetSuccess() {
		return OrderServiceGetOrderResult_Success_DEFAULT
	}
	return p.Success
}

var OrderServiceGetOrderResult_Err_DEFAULT *OrderError

func (p *OrderServiceGetOrderResult) GetErr() (v *OrderError) {
	if !p.IsSetErr() {
		return OrderServiceGetOrderResult_Err_DEFAULT
	}
	return p.Err
}
func (p *OrderServiceGetOrderResult) SetSuccess(x interface{}) {
	p.Success = x.(*GetOrderResponse)
}
func (p *OrderServiceGetOrderResult) SetErr(val *OrderError) {
	p.Err = val
}

func (p *OrderServiceGetOrderResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *OrderServiceGetOrderResult) IsSetErr() bool {
	return p.Err != nil
}

func (p *OrderServiceGetOrderResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("OrderServiceGetOrderResult(%+v)", *p)
}

var fieldIDToName_OrderServiceGetOrderResult = map[int16]string{
	0: "success",
	1: "err",
}

type OrderServiceUpdateStatusArgs struct {
	Req *UpdateStatusRequest `thrift:"req,1" frugal:"1,default,UpdateStatusRequest" json:"req"`
}

func NewOrderServiceUpdateStatusArgs() *OrderServiceUpdateStatusArgs {
	return &OrderServiceUpdateStatusArgs{}
}

func (p *OrderServiceUpdateStatusArgs) InitDefault() {
}

var OrderServiceUpdateStatusArgs_Req_DEFAULT *UpdateStatusRequest

func (p *OrderServiceUpdateStatusArgs) GetReq() (v *UpdateStatusRequest) {
	if !p.IsSetReq() {
		return OrderServiceUpdateStatusArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *OrderServiceUpdateStatusArgs) SetReq(val *UpdateStatusRequest) {
	p.Req = val
}

func (p *OrderServiceUpdateStatusArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *OrderServiceUpdateStatusArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("OrderServiceUpdateStatusArgs(%+v)", *p)
}

var fieldIDToName_OrderServiceUpdateStatusArgs = map[int16]string{
	1: "req",
}

type OrderServiceUpdateStatusResult struct {
	Success *UpdateStatusResponse `thrift:"success,0,optional" frugal:"0,optional,UpdateStatusResponse" json:"success,omitempty"`
	Err     *OrderError           `thrift:"err,1,optional" frugal:"1,optional,OrderError" json:"err,omitempty"`
}

func NewOrderServiceUpdateStatusResult() *OrderServiceUpdateStatusResult {
	return &OrderServiceUpdateStatusResult{}
}

func (p *OrderServiceUpdateStatusResult) InitDefault() {
}

var OrderServiceUpdateStatusResult_Success_DEFAULT *UpdateStatusResponse

func (p *OrderServiceUpdateStatusResult) GetSuccess() (v *UpdateStatusResponse) {
	if !p.IsSetSuccess() {
		return OrderServiceUpdateStatusResult_Success_DEFAULT
	}
	return p.Success
}

var OrderServiceUpdateStatusResult_Err_DEFAULT *OrderError

func (p *OrderServiceUpdateStatusResult) GetErr() (v *OrderError) {
	if !p.IsSetErr() {
		return OrderServiceUpdateStatusResult_Err_DEFAULT
	}
	return p.Err
}
func (p *OrderServiceUpdateStatusResult) SetSuccess(x interface{}) {
	p.Success = x.(*UpdateStatusResponse)
}
func (p *OrderServiceUpdateStatusResult) SetErr(val *OrderError) {
	p.Err = val
}

func (p *OrderServiceUpdateStatusResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *OrderServiceUpdateStatusResult) IsSetErr() bool {
	return p.Err != nil
}

func (p *OrderServiceUpdateStatusResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("OrderServiceUpdateStatusResult(%+v)", *p)
}

var fieldIDToName_OrderServiceUpdateStatusResult = map[int16]string{
	0: "success",
	1: "err",
}

// exceptions of methods in OrderService.
var (
	_ error = (*OrderError)(nil)
)
