// Code generated by thriftgo (0.4.5). DO NOT EDIT.

package user

import (
	"context"
	"fmt"
)

type Profile struct {
	UserId  string `thrift:"user_id,1" frugal:"1,default,string" json:"user_id"`
	Email   string `thrift:"email,2" frugal:"2,default,string" json:"email"`
	Address string `thrift:"address,3" frugal:"3,default,string" json:"address"`
}

func NewProfile() *Profile {
	return &Profile{}
}

func (p *Profile) InitDefault() {
}

func (p *Profile) GetUserId() (v string) {
	return p.UserId
}

func (p *Profile) GetEmail() (v string) {
	return p.Email
}

func (p *Profile) GetAddress() (v string) {
	return p.Address
}
func (p *Profile) SetUserId(val string) {
	p.UserId = val
}
func (p *Profile) SetEmail(val string) {
	p.Email = val
}
func (p *Profile) SetAddress(val string) {
	p.Address = val
}

func (p *Profile) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("Profile(%+v)", *p)
}

var fieldIDToName_Profile = map[int16]string{
	1: "user_id",
	2: "email",
	3: "address",
}

type Accessor struct {
	Actor  string `thrift:"actor,1,required" frugal:"1,required,string" json:"actor"`
	Reason string `thrift:"reason,2,required" frugal:"2,required,string" json:"reason"`
}

func NewAccessor() *Accessor {
	return &Accessor{}
}

func (p *Accessor) InitDefault() {
}

func (p *Accessor) GetActor() (v string) {
	return p.Actor
}

func (p *Accessor) GetReason() (v string) {
	return p.Reason
}
func (p *Accessor) SetActor(val string) {
	p.Actor = val
}
func (p *Accessor) SetReason(val string) {
	p.Reason = val
}

func (p *Accessor) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("Accessor(%+v)", *p)
}

var fieldIDToName_Accessor = map[int16]string{
	1: "actor",
	2: "reason",
}

type UpsertProfileRequest struct {
	UserId   string    `thrift:"user_id,1,required" frugal:"1,required,string" json:"user_id"`
	Email    string    `thrift:"email,2,required" frugal:"2,required,string" json:"email"`
	Address  *string   `thrift:"address,3,optional" frugal:"3,optional,string" json:"address,omitempty"`
	Accessor *Accessor `thrift:"accessor,4,required" frugal:"4,required,Accessor" json:"accessor"`
}

func NewUpsertProfileRequest() *UpsertProfileRequest {
	return &UpsertProfileRequest{}
}

func (p *UpsertProfileRequest) InitDefault() {
}

func (p *UpsertProfileRequest) GetUserId() (v string) {
	return p.UserId
}

func (p *UpsertProfileRequest) GetEmail() (v string) {
	return p.Email
}

var UpsertProfileRequest_Address_DEFAULT string

func (p *UpsertProfileRequest) GetAddress() (v string) {
	if !p.IsSetAddress() {
		return UpsertProfileRequest_Address_DEFAULT
	}
	return *p.Address
}

var UpsertProfileRequest_Accessor_DEFAULT *Accessor

func (p *UpsertProfileRequest) GetAccessor() (v *Accessor) {
	if !p.IsSetAccessor() {
		return UpsertProfileRequest_Accessor_DEFAULT
	}
	return p.Accessor
}
func (p *UpsertProfileRequest) SetUserId(val string) {
	p.UserId = val
}
func (p *UpsertProfileRequest) SetEmail(val string) {
	p.Email = val
}
func (p *UpsertProfileRequest) SetAddress(val *string) {
	p.Address = val
}
func (p *UpsertProfileRequest) SetAccessor(val *Accessor) {
	p.Accessor = val
}

func (p *UpsertProfileRequest) IsSetAddress() bool {
	return p.Address != nil
}

func (p *UpsertProfileRequest) IsSetAccessor() bool {
	return p.Accessor != nil
}

func (p *UpsertProfileRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UpsertProfileRequest(%+v)", *p)
}

var fieldIDToName_UpsertProfileRequest = map[int16]string{
	1: "user_id",
	2: "email",
	3: "address",
	4: "accessor",
}

type UpsertProfileResponse struct {
	Profile *Profile `thrift:"profile,1" frugal:"1,default,Profile" json:"profile"`
}

func NewUpsertProfileResponse() *UpsertProfileResponse {
	return &UpsertProfileResponse{}
}

func (p *UpsertProfileResponse) InitDefault() {
}

var UpsertProfileResponse_Profile_DEFAULT *Profile

func (p *UpsertProfileResponse) GetProfile() (v *Profile) {
	if !p.IsSetProfile() {
		return UpsertProfileResponse_Profile_DEFAULT
	}
	return p.Profile
}
func (p *UpsertProfileResponse) SetProfile(val *Profile) {
	p.Profile = val
}

func (p *UpsertProfileResponse) IsSetProfile() bool {
	return p.Profile != nil
}

func (p *UpsertProfileResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UpsertProfileResponse(%+v)", *p)
}

var fieldIDToName_UpsertProfileResponse = map[int16]string{
	1: "profile",
}

type GetProfileRequest struct {
	UserId   string    `thrift:"user_id,1,required" frugal:"1,required,string" json:"user_id"`
	Accessor *Accessor `thrift:"accessor,2,required" frugal:"2,required,Accessor" json:"accessor"`
}

func NewGetProfileRequest() *GetProfileRequest {
	return &GetProfileRequest{}
}

func (p *GetProfileRequest) InitDefault() {
}

func (p *GetProfileRequest) GetUserId() (v string) {
	return p.UserId
}

var GetProfileRequest_Accessor_DEFAULT *Accessor

func (p *GetProfileRequest) GetAccessor() (v *Accessor) {
	if !p.IsSetAccessor() {
		return GetProfileRequest_Accessor_DEFAULT
	}
	return p.Accessor
}
func (p *GetProfileRequest) SetUserId(val string) {
	p.UserId = val
}
func (p *GetProfileRequest) SetAccessor(val *Accessor) {
	p.Accessor = val
}

func (p *GetProfileRequest) IsSetAccessor() bool {
	return p.Accessor != nil
}

func (p *GetProfileRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetProfileRequest(%+v)", *p)
}

var fieldIDToName_GetProfileRequest = map[int16]string{
	1: "user_id",
	2: "accessor",
}

type GetProfileResponse struct {
	Profile *Profile `thrift:"profile,1" frugal:"1,default,Profile" json:"profile"`
}

func NewGetProfileResponse() *GetProfileResponse {
	return &GetProfileResponse{}
}

func (p *GetProfileResponse) InitDefault() {
}

var GetProfileResponse_Profile_DEFAULT *Profile

func (p *GetProfileResponse) GetProfile() (v *Profile) {
	if !p.IsSetProfile() {
		return GetProfileResponse_Profile_DEFAULT
	}
	return p.Profile
}
func (p *GetProfileResponse) SetProfile(val *Profile) {
	p.Profile = val
}

func (p *GetProfileResponse) IsSetProfile() bool {
	return p.Profile != nil
}

func (p *GetProfileResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetProfileResponse(%+v)", *p)
}

var fieldIDToName_GetProfileResponse = map[int16]string{
	1: "profile",
}

type DeleteUserRequest struct {
	UserId   string    `thrift:"user_id,1,required" frugal:"1,required,string" json:"user_id"`
	Accessor *Accessor `thrift:"accessor,2,required" frugal:"2,required,Accessor" json:"accessor"`
}

func NewDeleteUserRequest() *DeleteUserRequest {
	return &DeleteUserRequest{}
}

func (p *DeleteUserRequest) InitDefault() {
}

func (p *DeleteUserRequest) GetUserId() (v string) {
	return p.UserId
}

var DeleteUserRequest_Accessor_DEFAULT *Accessor

func (p *DeleteUserRequest) GetAccessor() (v *Accessor) {
	if !p.IsSetAccessor() {
		return DeleteUserRequest_Accessor_DEFAULT
	}
	return p.Accessor
}
func (p *DeleteUserRequest) SetUserId(val string) {
	p.UserId = val
}
func (p *DeleteUserRequest) SetAccessor(val *Accessor) {
	p.Accessor = val
}

func (p *DeleteUserRequest) IsSetAccessor() bool {
	return p.Accessor != nil
}

func (p *DeleteUserRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DeleteUserRequest(%+v)", *p)
}

var fieldIDToName_DeleteUserRequest = map[int16]string{
	1: "user_id",
	2: "accessor",
}

type DeleteUserResponse struct {
}

func NewDeleteUserResponse() *DeleteUserResponse {
	return &DeleteUserResponse{}
}

func (p *DeleteUserResponse) InitDefault() {
}

func (p *DeleteUserResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DeleteUserResponse(%+v)", *p)
}

var fieldIDToName_DeleteUserResponse = map[int16]string{}

type UserError struct {
	Code    int32  `thrift:"code,1" frugal:"1,default,i32" json:"code"`
	Message string `thrift:"message,2" frugal:"2,default,string" json:"message"`
}

func NewUserError() *UserError {
	return &UserError{}
}

func (p *UserError) InitDefault() {
}

func (p *UserError) GetCode() (v int32) {
	return p.Code
}

func (p *UserError) GetMessage() (v string) {
	return p.Message
}
func (p *UserError) SetCode(val int32) {
	p.Code = val
}
func (p *UserError) SetMessage(val string) {
	p.Message = val
}

func (p *UserError) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserError(%+v)", *p)
}
func (p *UserError) Error() string {
	return p.String()
}

var fieldIDToName_UserError = map[int16]string{
	1: "code",
	2: "message",
}

type UserService interface {
	UpsertProfile(ctx context.Context, req *UpsertProfileRequest) (r *UpsertProfileResponse, err error)

	GetProfile(ctx context.Context, req *GetProfileRequest) (r *GetProfileResponse, err error)

	DeleteUser(ctx context.Context, req *DeleteUserRequest) (r *DeleteUserResponse, err error)
}

type UserServiceUpsertProfileArgs struct {
	Req *UpsertProfileRequest `thrift:"req,1" frugal:"1,default,UpsertProfileRequest" json:"req"`
}

func NewUserServiceUpsertProfileArgs() *UserServiceUpsertProfileArgs {
	return &UserServiceUpsertProfileArgs{}
}

func (p *UserServiceUpsertProfileArgs) InitDefault() {
}

var UserServiceUpsertProfileArgs_Req_DEFAULT *UpsertProfileRequest

func (p *UserServiceUpsertProfileArgs) GetReq() (v *UpsertProfileRequest) {
	if !p.IsSetReq() {
		return UserServiceUpsertProfileArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *UserServiceUpsertProfileArgs) SetReq(val *UpsertProfileRequest) {
	p.Req = val
}

func (p *UserServiceUpsertProfileArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *UserServiceUpsertProfileArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceUpsertProfileArgs(%+v)", *p)
}

var fieldIDToName_UserServiceUpsertProfileArgs = map[int16]string{
	1: "req",
}

type UserServiceUpsertProfileResult struct {
	Success *UpsertProfileResponse `thrift:"success,0,optional" frugal:"0,optional,UpsertProfileResponse" json:"success,omitempty"`
	Err     *UserError             `thrift:"err,1,optional" frugal:"1,optional,UserError" json:"err,omitempty"`
}

func NewUserServiceUpsertProfileResult() *UserServiceUpsertProfileResult {
	return &UserServiceUpsertProfileResult{}
}

func (p *UserServiceUpsertProfileResult) InitDefault() {
}

var UserServiceUpsertProfileResult_Success_DEFAULT *UpsertProfileResponse

func (p *UserServiceUpsertProfileResult) GetSuccess() (v *UpsertProfileResponse) {
	if !p.IsSetSuccess() {
		return UserServiceUpsertProfileResult_Success_DEFAULT
	}
	return p.Success
}

var UserServiceUpsertProfileResult_Err_DEFAULT *UserError

func (p *UserServiceUpsertProfileResult) GetErr() (v *UserError) {
	if !p.IsSetErr() {
		return UserServiceUpsertProfileResult_Err_DEFAULT
	}
	return p.Err
}
func (p *UserServiceUpsertProfileResult) SetSuccess(x interface{}) {
	p.Success = x.(*UpsertProfileResponse)
}
func (p *UserServiceUpsertProfileResult) SetErr(val *UserError) {
	p.Err = val
}

func (p *UserServiceUpsertProfileResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UserServiceUpsertProfileResult) IsSetErr() bool {
	return p.Err != nil
}

func (p *UserServiceUpsertProfileResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceUpsertProfileResult(%+v)", *p)
}

var fieldIDToName_UserServiceUpsertProfileResult = map[int16]string{
	0: "success",
	1: "err",
}

type UserServiceGetProfileArgs struct {
	Req *GetProfileRequest `thrift:"req,1" frugal:"1,default,GetProfileRequest" json:"req"`
}

func NewUserServiceGetProfileArgs() *UserServiceGetProfileArgs {
	return &UserServiceGetProfileArgs{}
}

func (p *UserServiceGetProfileArgs) InitDefault() {
}

var UserServiceGetProfileArgs_Req_DEFAULT *GetProfileRequest

func (p *UserServiceGetProfileArgs) GetReq() (v *GetProfileRequest) {
	if !p.IsSetReq() {
		return UserServiceGetProfileArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *UserServiceGetProfileArgs) SetReq(val *GetProfileRequest) {
	p.Req = val
}

func (p *UserServiceGetProfileArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *UserServiceGetProfileArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceGetProfileArgs(%+v)", *p)
}

var fieldIDToName_UserServiceGetProfileArgs = map[int16]string{
	1: "req",
}

type UserServiceGetProfileResult struct {
	Success *GetProfileResponse `thrift:"success,0,optional" frugal:"0,optional,GetProfileResponse" json:"success,omitempty"`
	Err     *UserError          `thrift:"err,1,optional" frugal:"1,optional,UserError" json:"err,omitempty"`
}

func NewUserServiceGetProfileResult() *UserServiceGetProfileResult {
	return &UserServiceGetProfileResult{}
}

func (p *UserServiceGetProfileResult) InitDefault() {
}

var UserServiceGetProfileResult_Success_DEFAULT *GetProfileResponse

func (p *UserServiceGetProfileResult) GetSuccess() (v *GetProfileResponse) {
	if !p.IsSetSuccess() {
		return UserServiceGetProfileResult_Success_DEFAULT
	}
	return p.Success
}

var UserServiceGetProfileResult_Err_DEFAULT *UserError

func (p *UserServiceGetProfileResult) GetErr() (v *UserError) {
	if !p.IsSetErr() {
		return UserServiceGetProfileResult_Err_DEFAULT
	}
	return p.Err
}
func (p *UserServiceGetProfileResult) SetSuccess(x interface{}) {
	p.Success = x.(*GetProfileResponse)
}
func (p *UserServiceGetProfileResult) SetErr(val *UserError) {
	p.Err = val
}

func (p *UserServiceGetProfileResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UserServiceGetProfileResult) IsSetErr() bool {
	return p.Err != nil
}

func (p *UserServiceGetProfileResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceGetProfileResult(%+v)", *p)
}

var fieldIDToName_UserServiceGetProfileResult = map[int16]string{
	0: "success",
	1: "err",
}

type UserServiceDeleteUserArgs struct {
	Req *DeleteUserRequest `thrift:"req,1" frugal:"1,default,DeleteUserRequest" json:"req"`
}

func NewUserServiceDeleteUserArgs() *UserServiceDeleteUserArgs {
	return &UserServiceDeleteUserArgs{}
}

func (p *UserServiceDeleteUserArgs) InitDefault() {
}

var UserServiceDeleteUserArgs_Req_DEFAULT *DeleteUserRequest

func (p *UserServiceDeleteUserArgs) GetReq() (v *DeleteUserRequest) {
	if !p.IsSetReq() {
		return UserServiceDeleteUserArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *UserServiceDeleteUserArgs) SetReq(val *DeleteUserRequest) {
	p.Req = val
}

func (p *UserServiceDeleteUserArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *UserServiceDeleteUserArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceDeleteUserArgs(%+v)", *p)
}

var fieldIDToName_UserServiceDeleteUserArgs = map[int16]string{
	1: "req",
}

type UserServiceDeleteUserResult struct {
	Success *DeleteUserResponse `thrift:"success,0,optional" frugal:"0,optional,DeleteUserResponse" json:"success,omitempty"`
	Err     *UserError          `thrift:"err,1,optional" frugal:"1,optional,UserError" json:"err,omitempty"`
}

func NewUserServiceDeleteUserResult() *UserServiceDeleteUserResult {
	return &UserServiceDeleteUserResult{}
}

func (p *UserServiceDeleteUserResult) InitDefault() {
}

var UserServiceDeleteUserResult_Success_DEFAULT *DeleteUserResponse

func (p *UserServiceDeleteUserResult) GetSuccess() (v *DeleteUserResponse) {
	if !p.IsSetSuccess() {
		return UserServiceDeleteUserResult_Success_DEFAULT
	}
	return p.Success
}

var UserServiceDeleteUserResult_Err_DEFAULT *UserError

func (p *UserServiceDeleteUserResult) GetErr() (v *UserError) {
	if !p.IsSetErr() {
		return UserServiceDeleteUserResult_Err_DEFAULT
	}
	return p.Err
}
func (p *UserServiceDeleteUserResult) SetSuccess(x interface{}) {
	p.Success = x.(*DeleteUserResponse)
}
func (p *UserServiceDeleteUserResult) SetErr(val *UserError) {
	p.Err = val
}

func (p *UserServiceDeleteUserResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UserServiceDeleteUserResult) IsSetErr() bool {
	return p.Err != nil
}

func (p *UserServiceDeleteUserResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceDeleteUserResult(%+v)", *p)
}

var fieldIDToName_UserServiceDeleteUserResult = map[int16]string{
	0: "success",
	1: "err",
}

// exceptions of methods in UserService.
var (
	_ error = (*UserError)(nil)
)
