// Code generated by thriftgo (0.4.5). DO NOT EDIT.

package payment

import (
	"context"
	"fmt"
)

type Payment struct {
	PaymentId   string `thrift:"payment_id,1" frugal:"1,default,string" json:"payment_id"`
	OrderId     string `thrift:"order_id,2" frugal:"2,default,string" json:"order_id"`
	AmountCents int64  `thrift:"amount_cents,3" frugal:"3,default,i64" json:"amount_cents"`
	Status      string `thrift:"status,4" frugal:"4,default,string" json:"status"`
}

func NewPayment() *Payment {
	return &Payment{}
}

func (p *Payment) InitDefault() {
}

func (p *Payment) GetPaymentId() (v string) {
	return p.PaymentId
}

func (p *Payment) GetOrderId() (v string) {
	return p.OrderId
}

func (p *Payment) GetAmountCents() (v int64) {
	return p.AmountCents
}

func (p *Payment) GetStatus() (v string) {
	return p.Status
}
func (p *Payment) SetPaymentId(val string) {
	p.PaymentId = val
}
func (p *Payment) SetOrderId(val string) {
	p.OrderId = val
}
func (p *Payment) SetAmountCents(val int64) {
	p.AmountCents = val
}
func (p *Payment) SetStatus(val string) {
	p.Status = val
}

func (p *Payment) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("Payment(%+v)", *p)
}

var fieldIDToName_Payment = map[int16]string{
	1: "payment_id",
	2: "order_id",
	3: "amount_cents",
	4: "status",
}

type ChargeRequest struct {
	OrderId        string `thrift:"order_id,1,required" frugal:"1,required,string" json:"order_id"`
	AmountCents    int64  `thrift:"amount_cents,2,required" frugal:"2,required,i64" json:"amount_cents"`
	IdempotencyKey string `thrift:"idempotency_key,3,required" frugal:"3,required,string" json:"idempotency_key"`
}

func NewChargeRequest() *ChargeRequest {
	return &ChargeRequest{}
}

func (p *ChargeRequest) InitDefault() {
}

func (p *ChargeRequest) GetOrderId() (v string) {
	return p.OrderId
}

func (p *ChargeRequest) GetAmountCents() (v int64) {
	return p.AmountCents
}

func (p *ChargeRequest) GetIdempotencyKey() (v string) {
	return p.IdempotencyKey
}
func (p *ChargeRequest) SetOrderId(val string) {
	p.OrderId = val
}
func (p *ChargeRequest) SetAmountCents(val int64) {
	p.AmountCents = val
}
func (p *ChargeRequest) SetIdempotencyKey(val string) {
	p.IdempotencyKey = val
}

func (p *ChargeRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ChargeRequest(%+v)", *p)
}

var fieldIDToName_ChargeRequest = map[int16]string{
	1: "order_id",
	2: "amount_cents",
	3: "idempotency_key",
}

type ChargeResponse struct {
	Payment  *Payment `thrift:"payment,1" frugal:"1,default,Payment" json:"payment"`
	Replayed bool     `thrift:"replayed,2" frugal:"2,default,bool" json:"replayed"`
}

func NewChargeResponse() *ChargeResponse {
	return &ChargeResponse{}
}

func (p *ChargeResponse) InitDefault() {
}

var ChargeResponse_Payment_DEFAULT *Payment

func (p *ChargeResponse) GetPayment() (v *Payment) {
	if !p.IsSetPayment() {
		return ChargeResponse_Payment_DEFAULT
	}
	return p.Payment
}

func (p *ChargeResponse) GetReplayed() (v bool) {
	return p.Replayed
}
func (p *ChargeResponse) SetPayment(val *Payment) {
	p.Payment = val
}
func (p *ChargeResponse) SetReplayed(val bool) {
	p.Replayed = val
}

func (p *ChargeResponse) IsSetPayment() bool {
	return p.Payment != nil
}

func (p *ChargeResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ChargeResponse(%+v)", *p)
}

var fieldIDToName_ChargeResponse = map[int16]string{
	1: "payment",
	2: "replayed",
}

type PaymentError struct {
	Code    int32  `thrift:"code,1" frugal:"1,default,i32" json:"code"`
	Message string `thrift:"message,2" frugal:"2,default,string" json:"message"`
}

func NewPaymentError() *PaymentError {
	return &PaymentError{}
}

func (p *PaymentError) InitDefault() {
}

func (p *PaymentError) GetCode() (v int32) {
	return p.Code
}

func (p *PaymentError) GetMessage() (v string) {
	return p.Message
}
func (p *PaymentError) SetCode(val int32) {
	p.Code = val
}
func (p *PaymentError) SetMessage(val string) {
	p.Message = val
}

func (p *PaymentError) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PaymentError(%+v)", *p)
}
func (p *PaymentError) Error() string {
	return p.String()
}

var fieldIDToName_PaymentError = map[int16]string{
	1: "code",
	2: "message",
}

type PaymentService interface {
	Charge(ctx context.Context, req *ChargeRequest) (r *ChargeResponse, err error)
}

type PaymentServiceChargeArgs struct {
	Req *ChargeRequest `thrift:"req,1" frugal:"1,default,ChargeRequest" json:"req"`
}

func NewPaymentServiceChargeArgs() *PaymentServiceChargeArgs {
	return &PaymentServiceChargeArgs{}
}

func (p *PaymentServiceChargeArgs) InitDefault() {
}

var PaymentServiceChargeArgs_Req_DEFAULT *ChargeRequest

func (p *PaymentServiceChargeArgs) GetReq() (v *ChargeRequest) {
	if !p.IsSetReq() {
		return PaymentServiceChargeArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *PaymentServiceChargeArgs) SetReq(val *ChargeRequest) {
	p.Req = val
}

func (p *PaymentServiceChargeArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *PaymentServiceChargeArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PaymentServiceChargeArgs(%+v)", *p)
}

var fieldIDToName_PaymentServiceChargeArgs = map[int16]string{
	1: "req",
}

type PaymentServiceChargeResult struct {
	Success *ChargeResponse `thrift:"success,0,optional" frugal:"0,optional,ChargeResponse" json:"success,omitempty"`
	Err     *PaymentError   `thrift:"err,1,optional" frugal:"1,optional,PaymentError" json:"err,omitempty"`
}

func NewPaymentServiceChargeResult() *PaymentServiceChargeResult {
	return &PaymentServiceChargeResult{}
}

func (p *PaymentServiceChargeResult) InitDefault() {
}

var PaymentServiceChargeResult_Success_DEFAULT *ChargeResponse

func (p *PaymentServiceChargeResult) GetSuccess() (v *ChargeResponse) {
	if !p.IsSetSuccess() {
		return PaymentServiceChargeResult_Success_DEFAULT
	}
	return p.Success
}

var PaymentServiceChargeResult_Err_DEFAULT *PaymentError

func (p *PaymentServiceChargeResult) GetErr() (v *PaymentError) {
	if !p.IsSetErr() {
		return PaymentServiceChargeResult_Err_DEFAULT
	}
	return p.Err
}
func (p *PaymentServiceChargeResult) SetSuccess(x interface{}) {
	p.Success = x.(*ChargeResponse)
}
func (p *PaymentServiceChargeResult) SetErr(val *PaymentError) {
	p.Err = val
}

func (p *PaymentServiceChargeResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *PaymentServiceChargeResult) IsSetErr() bool {
	return p.Err != nil
}

func (p *PaymentServiceChargeResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PaymentServiceChargeResult(%+v)", *p)
}

var fieldIDToName_PaymentServiceChargeResult = map[int16]string{
	0: "success",
	1: "err",
}

// exceptions of methods in PaymentService.
var (
	_ error = (*PaymentError)(nil)
)
